#!/bin/sh
scriptdir=`dirname $0`

sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp1.txt > ../../private_data/odnb_data_text/proc_STAN/ST_1.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp2.txt > ../../private_data/odnb_data_text/proc_STAN/ST_2.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp3.txt > ../../private_data/odnb_data_text/proc_STAN/ST_3.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp4.txt > ../../private_data/odnb_data_text/proc_STAN/ST_4.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp5.txt > ../../private_data/odnb_data_text/proc_STAN/ST_5.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp6.txt > ../../private_data/odnb_data_text/proc_STAN/ST_6.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp7.txt > ../../private_data/odnb_data_text/proc_STAN/ST_7.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp8.txt > ../../private_data/odnb_data_text/proc_STAN/ST_8.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp9.txt > ../../private_data/odnb_data_text/proc_STAN/ST_9.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp10.txt > ../../private_data/odnb_data_text/proc_STAN/ST_10.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp11.txt > ../../private_data/odnb_data_text/proc_STAN/ST_11.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp12.txt > ../../private_data/odnb_data_text/proc_STAN/ST_12.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp13.txt > ../../private_data/odnb_data_text/proc_STAN/ST_13.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp14.txt > ../../private_data/odnb_data_text/proc_STAN/ST_14.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp15.txt > ../../private_data/odnb_data_text/proc_STAN/ST_15.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp16.txt > ../../private_data/odnb_data_text/proc_STAN/ST_16.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp17.txt > ../../private_data/odnb_data_text/proc_STAN/ST_17.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp18.txt > ../../private_data/odnb_data_text/proc_STAN/ST_18.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp19.txt > ../../private_data/odnb_data_text/proc_STAN/ST_19.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp20.txt > ../../private_data/odnb_data_text/proc_STAN/ST_20.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp21.txt > ../../private_data/odnb_data_text/proc_STAN/ST_21.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp22.txt > ../../private_data/odnb_data_text/proc_STAN/ST_22.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp23.txt > ../../private_data/odnb_data_text/proc_STAN/ST_23.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp24.txt > ../../private_data/odnb_data_text/proc_STAN/ST_24.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp25.txt > ../../private_data/odnb_data_text/proc_STAN/ST_25.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp26.txt > ../../private_data/odnb_data_text/proc_STAN/ST_26.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp27.txt > ../../private_data/odnb_data_text/proc_STAN/ST_27.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp28.txt > ../../private_data/odnb_data_text/proc_STAN/ST_28.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp29.txt > ../../private_data/odnb_data_text/proc_STAN/ST_29.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp30.txt > ../../private_data/odnb_data_text/proc_STAN/ST_30.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp31.txt > ../../private_data/odnb_data_text/proc_STAN/ST_31.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp32.txt > ../../private_data/odnb_data_text/proc_STAN/ST_32.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp33.txt > ../../private_data/odnb_data_text/proc_STAN/ST_33.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp34.txt > ../../private_data/odnb_data_text/proc_STAN/ST_34.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp35.txt > ../../private_data/odnb_data_text/proc_STAN/ST_35.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp36.txt > ../../private_data/odnb_data_text/proc_STAN/ST_36.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp37.txt > ../../private_data/odnb_data_text/proc_STAN/ST_37.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp38.txt > ../../private_data/odnb_data_text/proc_STAN/ST_38.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp39.txt > ../../private_data/odnb_data_text/proc_STAN/ST_39.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp40.txt > ../../private_data/odnb_data_text/proc_STAN/ST_40.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp41.txt > ../../private_data/odnb_data_text/proc_STAN/ST_41.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp42.txt > ../../private_data/odnb_data_text/proc_STAN/ST_42.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp43.txt > ../../private_data/odnb_data_text/proc_STAN/ST_43.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp44.txt > ../../private_data/odnb_data_text/proc_STAN/ST_44.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp45.txt > ../../private_data/odnb_data_text/proc_STAN/ST_45.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp46.txt > ../../private_data/odnb_data_text/proc_STAN/ST_46.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp47.txt > ../../private_data/odnb_data_text/proc_STAN/ST_47.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp48.txt > ../../private_data/odnb_data_text/proc_STAN/ST_48.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp49.txt > ../../private_data/odnb_data_text/proc_STAN/ST_49.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp50.txt > ../../private_data/odnb_data_text/proc_STAN/ST_50.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp51.txt > ../../private_data/odnb_data_text/proc_STAN/ST_51.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp52.txt > ../../private_data/odnb_data_text/proc_STAN/ST_52.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp53.txt > ../../private_data/odnb_data_text/proc_STAN/ST_53.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp54.txt > ../../private_data/odnb_data_text/proc_STAN/ST_54.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp55.txt > ../../private_data/odnb_data_text/proc_STAN/ST_55.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp56.txt > ../../private_data/odnb_data_text/proc_STAN/ST_56.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp57.txt > ../../private_data/odnb_data_text/proc_STAN/ST_57.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp58.txt > ../../private_data/odnb_data_text/proc_STAN/ST_58.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp59.txt > ../../private_data/odnb_data_text/proc_STAN/ST_59.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp60.txt > ../../private_data/odnb_data_text/proc_STAN/ST_60.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp61.txt > ../../private_data/odnb_data_text/proc_STAN/ST_61.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp62.txt > ../../private_data/odnb_data_text/proc_STAN/ST_62.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp63.txt > ../../private_data/odnb_data_text/proc_STAN/ST_63.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp64.txt > ../../private_data/odnb_data_text/proc_STAN/ST_64.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp65.txt > ../../private_data/odnb_data_text/proc_STAN/ST_65.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp66.txt > ../../private_data/odnb_data_text/proc_STAN/ST_66.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp67.txt > ../../private_data/odnb_data_text/proc_STAN/ST_67.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp68.txt > ../../private_data/odnb_data_text/proc_STAN/ST_68.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp69.txt > ../../private_data/odnb_data_text/proc_STAN/ST_69.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp70.txt > ../../private_data/odnb_data_text/proc_STAN/ST_70.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp71.txt > ../../private_data/odnb_data_text/proc_STAN/ST_71.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp72.txt > ../../private_data/odnb_data_text/proc_STAN/ST_72.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp73.txt > ../../private_data/odnb_data_text/proc_STAN/ST_73.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp74.txt > ../../private_data/odnb_data_text/proc_STAN/ST_74.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp75.txt > ../../private_data/odnb_data_text/proc_STAN/ST_75.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp76.txt > ../../private_data/odnb_data_text/proc_STAN/ST_76.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp77.txt > ../../private_data/odnb_data_text/proc_STAN/ST_77.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp78.txt > ../../private_data/odnb_data_text/proc_STAN/ST_78.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp79.txt > ../../private_data/odnb_data_text/proc_STAN/ST_79.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp80.txt > ../../private_data/odnb_data_text/proc_STAN/ST_80.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp81.txt > ../../private_data/odnb_data_text/proc_STAN/ST_81.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp82.txt > ../../private_data/odnb_data_text/proc_STAN/ST_82.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp83.txt > ../../private_data/odnb_data_text/proc_STAN/ST_83.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp84.txt > ../../private_data/odnb_data_text/proc_STAN/ST_84.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp85.txt > ../../private_data/odnb_data_text/proc_STAN/ST_85.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp86.txt > ../../private_data/odnb_data_text/proc_STAN/ST_86.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp87.txt > ../../private_data/odnb_data_text/proc_STAN/ST_87.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp88.txt > ../../private_data/odnb_data_text/proc_STAN/ST_88.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp89.txt > ../../private_data/odnb_data_text/proc_STAN/ST_89.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp90.txt > ../../private_data/odnb_data_text/proc_STAN/ST_90.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp91.txt > ../../private_data/odnb_data_text/proc_STAN/ST_91.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp92.txt > ../../private_data/odnb_data_text/proc_STAN/ST_92.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp93.txt > ../../private_data/odnb_data_text/proc_STAN/ST_93.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp94.txt > ../../private_data/odnb_data_text/proc_STAN/ST_94.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp95.txt > ../../private_data/odnb_data_text/proc_STAN/ST_95.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp96.txt > ../../private_data/odnb_data_text/proc_STAN/ST_96.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp97.txt > ../../private_data/odnb_data_text/proc_STAN/ST_97.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp98.txt > ../../private_data/odnb_data_text/proc_STAN/ST_98.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp99.txt > ../../private_data/odnb_data_text/proc_STAN/ST_99.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp100.txt > ../../private_data/odnb_data_text/proc_STAN/ST_100.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp101.txt > ../../private_data/odnb_data_text/proc_STAN/ST_101.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp102.txt > ../../private_data/odnb_data_text/proc_STAN/ST_102.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp103.txt > ../../private_data/odnb_data_text/proc_STAN/ST_103.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp104.txt > ../../private_data/odnb_data_text/proc_STAN/ST_104.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp105.txt > ../../private_data/odnb_data_text/proc_STAN/ST_105.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp106.txt > ../../private_data/odnb_data_text/proc_STAN/ST_106.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp107.txt > ../../private_data/odnb_data_text/proc_STAN/ST_107.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp108.txt > ../../private_data/odnb_data_text/proc_STAN/ST_108.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp109.txt > ../../private_data/odnb_data_text/proc_STAN/ST_109.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp110.txt > ../../private_data/odnb_data_text/proc_STAN/ST_110.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp111.txt > ../../private_data/odnb_data_text/proc_STAN/ST_111.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp112.txt > ../../private_data/odnb_data_text/proc_STAN/ST_112.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp113.txt > ../../private_data/odnb_data_text/proc_STAN/ST_113.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp114.txt > ../../private_data/odnb_data_text/proc_STAN/ST_114.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp115.txt > ../../private_data/odnb_data_text/proc_STAN/ST_115.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp116.txt > ../../private_data/odnb_data_text/proc_STAN/ST_116.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp117.txt > ../../private_data/odnb_data_text/proc_STAN/ST_117.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp118.txt > ../../private_data/odnb_data_text/proc_STAN/ST_118.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp119.txt > ../../private_data/odnb_data_text/proc_STAN/ST_119.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp120.txt > ../../private_data/odnb_data_text/proc_STAN/ST_120.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp121.txt > ../../private_data/odnb_data_text/proc_STAN/ST_121.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp122.txt > ../../private_data/odnb_data_text/proc_STAN/ST_122.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp123.txt > ../../private_data/odnb_data_text/proc_STAN/ST_123.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp124.txt > ../../private_data/odnb_data_text/proc_STAN/ST_124.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp125.txt > ../../private_data/odnb_data_text/proc_STAN/ST_125.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp126.txt > ../../private_data/odnb_data_text/proc_STAN/ST_126.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp127.txt > ../../private_data/odnb_data_text/proc_STAN/ST_127.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp128.txt > ../../private_data/odnb_data_text/proc_STAN/ST_128.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp129.txt > ../../private_data/odnb_data_text/proc_STAN/ST_129.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp130.txt > ../../private_data/odnb_data_text/proc_STAN/ST_130.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp131.txt > ../../private_data/odnb_data_text/proc_STAN/ST_131.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp132.txt > ../../private_data/odnb_data_text/proc_STAN/ST_132.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp133.txt > ../../private_data/odnb_data_text/proc_STAN/ST_133.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp134.txt > ../../private_data/odnb_data_text/proc_STAN/ST_134.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp135.txt > ../../private_data/odnb_data_text/proc_STAN/ST_135.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp136.txt > ../../private_data/odnb_data_text/proc_STAN/ST_136.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp137.txt > ../../private_data/odnb_data_text/proc_STAN/ST_137.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp138.txt > ../../private_data/odnb_data_text/proc_STAN/ST_138.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp139.txt > ../../private_data/odnb_data_text/proc_STAN/ST_139.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp140.txt > ../../private_data/odnb_data_text/proc_STAN/ST_140.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp141.txt > ../../private_data/odnb_data_text/proc_STAN/ST_141.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp142.txt > ../../private_data/odnb_data_text/proc_STAN/ST_142.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp143.txt > ../../private_data/odnb_data_text/proc_STAN/ST_143.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp144.txt > ../../private_data/odnb_data_text/proc_STAN/ST_144.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp145.txt > ../../private_data/odnb_data_text/proc_STAN/ST_145.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp146.txt > ../../private_data/odnb_data_text/proc_STAN/ST_146.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp147.txt > ../../private_data/odnb_data_text/proc_STAN/ST_147.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp148.txt > ../../private_data/odnb_data_text/proc_STAN/ST_148.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp149.txt > ../../private_data/odnb_data_text/proc_STAN/ST_149.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp150.txt > ../../private_data/odnb_data_text/proc_STAN/ST_150.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp151.txt > ../../private_data/odnb_data_text/proc_STAN/ST_151.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp152.txt > ../../private_data/odnb_data_text/proc_STAN/ST_152.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp153.txt > ../../private_data/odnb_data_text/proc_STAN/ST_153.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp154.txt > ../../private_data/odnb_data_text/proc_STAN/ST_154.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp155.txt > ../../private_data/odnb_data_text/proc_STAN/ST_155.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp156.txt > ../../private_data/odnb_data_text/proc_STAN/ST_156.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp157.txt > ../../private_data/odnb_data_text/proc_STAN/ST_157.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp158.txt > ../../private_data/odnb_data_text/proc_STAN/ST_158.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp159.txt > ../../private_data/odnb_data_text/proc_STAN/ST_159.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp160.txt > ../../private_data/odnb_data_text/proc_STAN/ST_160.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp161.txt > ../../private_data/odnb_data_text/proc_STAN/ST_161.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp162.txt > ../../private_data/odnb_data_text/proc_STAN/ST_162.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp163.txt > ../../private_data/odnb_data_text/proc_STAN/ST_163.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp164.txt > ../../private_data/odnb_data_text/proc_STAN/ST_164.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp165.txt > ../../private_data/odnb_data_text/proc_STAN/ST_165.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp166.txt > ../../private_data/odnb_data_text/proc_STAN/ST_166.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp167.txt > ../../private_data/odnb_data_text/proc_STAN/ST_167.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp168.txt > ../../private_data/odnb_data_text/proc_STAN/ST_168.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp169.txt > ../../private_data/odnb_data_text/proc_STAN/ST_169.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp170.txt > ../../private_data/odnb_data_text/proc_STAN/ST_170.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp171.txt > ../../private_data/odnb_data_text/proc_STAN/ST_171.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp172.txt > ../../private_data/odnb_data_text/proc_STAN/ST_172.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp173.txt > ../../private_data/odnb_data_text/proc_STAN/ST_173.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp174.txt > ../../private_data/odnb_data_text/proc_STAN/ST_174.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp175.txt > ../../private_data/odnb_data_text/proc_STAN/ST_175.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp176.txt > ../../private_data/odnb_data_text/proc_STAN/ST_176.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp177.txt > ../../private_data/odnb_data_text/proc_STAN/ST_177.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp178.txt > ../../private_data/odnb_data_text/proc_STAN/ST_178.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp179.txt > ../../private_data/odnb_data_text/proc_STAN/ST_179.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp180.txt > ../../private_data/odnb_data_text/proc_STAN/ST_180.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp181.txt > ../../private_data/odnb_data_text/proc_STAN/ST_181.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp182.txt > ../../private_data/odnb_data_text/proc_STAN/ST_182.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp183.txt > ../../private_data/odnb_data_text/proc_STAN/ST_183.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp184.txt > ../../private_data/odnb_data_text/proc_STAN/ST_184.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp185.txt > ../../private_data/odnb_data_text/proc_STAN/ST_185.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp186.txt > ../../private_data/odnb_data_text/proc_STAN/ST_186.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp187.txt > ../../private_data/odnb_data_text/proc_STAN/ST_187.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp188.txt > ../../private_data/odnb_data_text/proc_STAN/ST_188.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp189.txt > ../../private_data/odnb_data_text/proc_STAN/ST_189.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp190.txt > ../../private_data/odnb_data_text/proc_STAN/ST_190.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp191.txt > ../../private_data/odnb_data_text/proc_STAN/ST_191.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp192.txt > ../../private_data/odnb_data_text/proc_STAN/ST_192.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp193.txt > ../../private_data/odnb_data_text/proc_STAN/ST_193.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp194.txt > ../../private_data/odnb_data_text/proc_STAN/ST_194.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp195.txt > ../../private_data/odnb_data_text/proc_STAN/ST_195.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp196.txt > ../../private_data/odnb_data_text/proc_STAN/ST_196.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp197.txt > ../../private_data/odnb_data_text/proc_STAN/ST_197.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp198.txt > ../../private_data/odnb_data_text/proc_STAN/ST_198.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp199.txt > ../../private_data/odnb_data_text/proc_STAN/ST_199.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp200.txt > ../../private_data/odnb_data_text/proc_STAN/ST_200.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp201.txt > ../../private_data/odnb_data_text/proc_STAN/ST_201.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp202.txt > ../../private_data/odnb_data_text/proc_STAN/ST_202.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp203.txt > ../../private_data/odnb_data_text/proc_STAN/ST_203.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp204.txt > ../../private_data/odnb_data_text/proc_STAN/ST_204.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp205.txt > ../../private_data/odnb_data_text/proc_STAN/ST_205.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp206.txt > ../../private_data/odnb_data_text/proc_STAN/ST_206.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp207.txt > ../../private_data/odnb_data_text/proc_STAN/ST_207.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp208.txt > ../../private_data/odnb_data_text/proc_STAN/ST_208.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp209.txt > ../../private_data/odnb_data_text/proc_STAN/ST_209.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp210.txt > ../../private_data/odnb_data_text/proc_STAN/ST_210.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp211.txt > ../../private_data/odnb_data_text/proc_STAN/ST_211.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp212.txt > ../../private_data/odnb_data_text/proc_STAN/ST_212.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp213.txt > ../../private_data/odnb_data_text/proc_STAN/ST_213.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp214.txt > ../../private_data/odnb_data_text/proc_STAN/ST_214.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp215.txt > ../../private_data/odnb_data_text/proc_STAN/ST_215.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp216.txt > ../../private_data/odnb_data_text/proc_STAN/ST_216.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp217.txt > ../../private_data/odnb_data_text/proc_STAN/ST_217.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp218.txt > ../../private_data/odnb_data_text/proc_STAN/ST_218.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp219.txt > ../../private_data/odnb_data_text/proc_STAN/ST_219.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp220.txt > ../../private_data/odnb_data_text/proc_STAN/ST_220.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp221.txt > ../../private_data/odnb_data_text/proc_STAN/ST_221.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp222.txt > ../../private_data/odnb_data_text/proc_STAN/ST_222.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp223.txt > ../../private_data/odnb_data_text/proc_STAN/ST_223.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp224.txt > ../../private_data/odnb_data_text/proc_STAN/ST_224.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp225.txt > ../../private_data/odnb_data_text/proc_STAN/ST_225.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp226.txt > ../../private_data/odnb_data_text/proc_STAN/ST_226.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp227.txt > ../../private_data/odnb_data_text/proc_STAN/ST_227.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp228.txt > ../../private_data/odnb_data_text/proc_STAN/ST_228.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp229.txt > ../../private_data/odnb_data_text/proc_STAN/ST_229.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp230.txt > ../../private_data/odnb_data_text/proc_STAN/ST_230.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp231.txt > ../../private_data/odnb_data_text/proc_STAN/ST_231.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp232.txt > ../../private_data/odnb_data_text/proc_STAN/ST_232.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp233.txt > ../../private_data/odnb_data_text/proc_STAN/ST_233.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp234.txt > ../../private_data/odnb_data_text/proc_STAN/ST_234.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp235.txt > ../../private_data/odnb_data_text/proc_STAN/ST_235.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp236.txt > ../../private_data/odnb_data_text/proc_STAN/ST_236.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp237.txt > ../../private_data/odnb_data_text/proc_STAN/ST_237.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp238.txt > ../../private_data/odnb_data_text/proc_STAN/ST_238.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp239.txt > ../../private_data/odnb_data_text/proc_STAN/ST_239.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp240.txt > ../../private_data/odnb_data_text/proc_STAN/ST_240.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp241.txt > ../../private_data/odnb_data_text/proc_STAN/ST_241.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp242.txt > ../../private_data/odnb_data_text/proc_STAN/ST_242.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp243.txt > ../../private_data/odnb_data_text/proc_STAN/ST_243.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp244.txt > ../../private_data/odnb_data_text/proc_STAN/ST_244.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp245.txt > ../../private_data/odnb_data_text/proc_STAN/ST_245.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp246.txt > ../../private_data/odnb_data_text/proc_STAN/ST_246.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp247.txt > ../../private_data/odnb_data_text/proc_STAN/ST_247.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp248.txt > ../../private_data/odnb_data_text/proc_STAN/ST_248.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp249.txt > ../../private_data/odnb_data_text/proc_STAN/ST_249.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp250.txt > ../../private_data/odnb_data_text/proc_STAN/ST_250.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp251.txt > ../../private_data/odnb_data_text/proc_STAN/ST_251.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp252.txt > ../../private_data/odnb_data_text/proc_STAN/ST_252.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp253.txt > ../../private_data/odnb_data_text/proc_STAN/ST_253.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp254.txt > ../../private_data/odnb_data_text/proc_STAN/ST_254.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp255.txt > ../../private_data/odnb_data_text/proc_STAN/ST_255.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp256.txt > ../../private_data/odnb_data_text/proc_STAN/ST_256.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp257.txt > ../../private_data/odnb_data_text/proc_STAN/ST_257.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp258.txt > ../../private_data/odnb_data_text/proc_STAN/ST_258.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp259.txt > ../../private_data/odnb_data_text/proc_STAN/ST_259.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp260.txt > ../../private_data/odnb_data_text/proc_STAN/ST_260.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp261.txt > ../../private_data/odnb_data_text/proc_STAN/ST_261.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp262.txt > ../../private_data/odnb_data_text/proc_STAN/ST_262.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp263.txt > ../../private_data/odnb_data_text/proc_STAN/ST_263.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp264.txt > ../../private_data/odnb_data_text/proc_STAN/ST_264.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp265.txt > ../../private_data/odnb_data_text/proc_STAN/ST_265.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp266.txt > ../../private_data/odnb_data_text/proc_STAN/ST_266.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp267.txt > ../../private_data/odnb_data_text/proc_STAN/ST_267.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp268.txt > ../../private_data/odnb_data_text/proc_STAN/ST_268.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp269.txt > ../../private_data/odnb_data_text/proc_STAN/ST_269.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp270.txt > ../../private_data/odnb_data_text/proc_STAN/ST_270.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp271.txt > ../../private_data/odnb_data_text/proc_STAN/ST_271.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp272.txt > ../../private_data/odnb_data_text/proc_STAN/ST_272.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp273.txt > ../../private_data/odnb_data_text/proc_STAN/ST_273.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp274.txt > ../../private_data/odnb_data_text/proc_STAN/ST_274.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp275.txt > ../../private_data/odnb_data_text/proc_STAN/ST_275.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp276.txt > ../../private_data/odnb_data_text/proc_STAN/ST_276.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp277.txt > ../../private_data/odnb_data_text/proc_STAN/ST_277.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp278.txt > ../../private_data/odnb_data_text/proc_STAN/ST_278.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp279.txt > ../../private_data/odnb_data_text/proc_STAN/ST_279.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp280.txt > ../../private_data/odnb_data_text/proc_STAN/ST_280.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp281.txt > ../../private_data/odnb_data_text/proc_STAN/ST_281.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp282.txt > ../../private_data/odnb_data_text/proc_STAN/ST_282.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp283.txt > ../../private_data/odnb_data_text/proc_STAN/ST_283.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp284.txt > ../../private_data/odnb_data_text/proc_STAN/ST_284.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp285.txt > ../../private_data/odnb_data_text/proc_STAN/ST_285.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp286.txt > ../../private_data/odnb_data_text/proc_STAN/ST_286.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp287.txt > ../../private_data/odnb_data_text/proc_STAN/ST_287.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp288.txt > ../../private_data/odnb_data_text/proc_STAN/ST_288.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp289.txt > ../../private_data/odnb_data_text/proc_STAN/ST_289.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp290.txt > ../../private_data/odnb_data_text/proc_STAN/ST_290.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp291.txt > ../../private_data/odnb_data_text/proc_STAN/ST_291.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp292.txt > ../../private_data/odnb_data_text/proc_STAN/ST_292.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp293.txt > ../../private_data/odnb_data_text/proc_STAN/ST_293.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp294.txt > ../../private_data/odnb_data_text/proc_STAN/ST_294.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp295.txt > ../../private_data/odnb_data_text/proc_STAN/ST_295.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp296.txt > ../../private_data/odnb_data_text/proc_STAN/ST_296.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp297.txt > ../../private_data/odnb_data_text/proc_STAN/ST_297.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp298.txt > ../../private_data/odnb_data_text/proc_STAN/ST_298.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp299.txt > ../../private_data/odnb_data_text/proc_STAN/ST_299.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp300.txt > ../../private_data/odnb_data_text/proc_STAN/ST_300.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp301.txt > ../../private_data/odnb_data_text/proc_STAN/ST_301.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp302.txt > ../../private_data/odnb_data_text/proc_STAN/ST_302.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp303.txt > ../../private_data/odnb_data_text/proc_STAN/ST_303.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp304.txt > ../../private_data/odnb_data_text/proc_STAN/ST_304.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp305.txt > ../../private_data/odnb_data_text/proc_STAN/ST_305.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp306.txt > ../../private_data/odnb_data_text/proc_STAN/ST_306.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp307.txt > ../../private_data/odnb_data_text/proc_STAN/ST_307.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp308.txt > ../../private_data/odnb_data_text/proc_STAN/ST_308.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp309.txt > ../../private_data/odnb_data_text/proc_STAN/ST_309.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp310.txt > ../../private_data/odnb_data_text/proc_STAN/ST_310.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp311.txt > ../../private_data/odnb_data_text/proc_STAN/ST_311.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp312.txt > ../../private_data/odnb_data_text/proc_STAN/ST_312.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp313.txt > ../../private_data/odnb_data_text/proc_STAN/ST_313.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp314.txt > ../../private_data/odnb_data_text/proc_STAN/ST_314.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp315.txt > ../../private_data/odnb_data_text/proc_STAN/ST_315.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp316.txt > ../../private_data/odnb_data_text/proc_STAN/ST_316.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp317.txt > ../../private_data/odnb_data_text/proc_STAN/ST_317.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp318.txt > ../../private_data/odnb_data_text/proc_STAN/ST_318.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp319.txt > ../../private_data/odnb_data_text/proc_STAN/ST_319.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp320.txt > ../../private_data/odnb_data_text/proc_STAN/ST_320.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp321.txt > ../../private_data/odnb_data_text/proc_STAN/ST_321.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp322.txt > ../../private_data/odnb_data_text/proc_STAN/ST_322.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp323.txt > ../../private_data/odnb_data_text/proc_STAN/ST_323.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp324.txt > ../../private_data/odnb_data_text/proc_STAN/ST_324.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp325.txt > ../../private_data/odnb_data_text/proc_STAN/ST_325.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp326.txt > ../../private_data/odnb_data_text/proc_STAN/ST_326.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp327.txt > ../../private_data/odnb_data_text/proc_STAN/ST_327.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp328.txt > ../../private_data/odnb_data_text/proc_STAN/ST_328.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp329.txt > ../../private_data/odnb_data_text/proc_STAN/ST_329.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp330.txt > ../../private_data/odnb_data_text/proc_STAN/ST_330.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp331.txt > ../../private_data/odnb_data_text/proc_STAN/ST_331.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp332.txt > ../../private_data/odnb_data_text/proc_STAN/ST_332.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp333.txt > ../../private_data/odnb_data_text/proc_STAN/ST_333.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp334.txt > ../../private_data/odnb_data_text/proc_STAN/ST_334.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp335.txt > ../../private_data/odnb_data_text/proc_STAN/ST_335.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp336.txt > ../../private_data/odnb_data_text/proc_STAN/ST_336.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp337.txt > ../../private_data/odnb_data_text/proc_STAN/ST_337.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp338.txt > ../../private_data/odnb_data_text/proc_STAN/ST_338.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp339.txt > ../../private_data/odnb_data_text/proc_STAN/ST_339.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp340.txt > ../../private_data/odnb_data_text/proc_STAN/ST_340.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp341.txt > ../../private_data/odnb_data_text/proc_STAN/ST_341.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp342.txt > ../../private_data/odnb_data_text/proc_STAN/ST_342.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp343.txt > ../../private_data/odnb_data_text/proc_STAN/ST_343.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp344.txt > ../../private_data/odnb_data_text/proc_STAN/ST_344.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp345.txt > ../../private_data/odnb_data_text/proc_STAN/ST_345.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp346.txt > ../../private_data/odnb_data_text/proc_STAN/ST_346.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp347.txt > ../../private_data/odnb_data_text/proc_STAN/ST_347.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp348.txt > ../../private_data/odnb_data_text/proc_STAN/ST_348.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp349.txt > ../../private_data/odnb_data_text/proc_STAN/ST_349.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp350.txt > ../../private_data/odnb_data_text/proc_STAN/ST_350.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp351.txt > ../../private_data/odnb_data_text/proc_STAN/ST_351.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp352.txt > ../../private_data/odnb_data_text/proc_STAN/ST_352.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp353.txt > ../../private_data/odnb_data_text/proc_STAN/ST_353.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp354.txt > ../../private_data/odnb_data_text/proc_STAN/ST_354.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp355.txt > ../../private_data/odnb_data_text/proc_STAN/ST_355.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp356.txt > ../../private_data/odnb_data_text/proc_STAN/ST_356.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp357.txt > ../../private_data/odnb_data_text/proc_STAN/ST_357.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp358.txt > ../../private_data/odnb_data_text/proc_STAN/ST_358.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp359.txt > ../../private_data/odnb_data_text/proc_STAN/ST_359.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp360.txt > ../../private_data/odnb_data_text/proc_STAN/ST_360.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp361.txt > ../../private_data/odnb_data_text/proc_STAN/ST_361.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp362.txt > ../../private_data/odnb_data_text/proc_STAN/ST_362.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp363.txt > ../../private_data/odnb_data_text/proc_STAN/ST_363.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp364.txt > ../../private_data/odnb_data_text/proc_STAN/ST_364.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp365.txt > ../../private_data/odnb_data_text/proc_STAN/ST_365.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp366.txt > ../../private_data/odnb_data_text/proc_STAN/ST_366.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp367.txt > ../../private_data/odnb_data_text/proc_STAN/ST_367.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp368.txt > ../../private_data/odnb_data_text/proc_STAN/ST_368.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp369.txt > ../../private_data/odnb_data_text/proc_STAN/ST_369.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp370.txt > ../../private_data/odnb_data_text/proc_STAN/ST_370.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp371.txt > ../../private_data/odnb_data_text/proc_STAN/ST_371.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp372.txt > ../../private_data/odnb_data_text/proc_STAN/ST_372.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp373.txt > ../../private_data/odnb_data_text/proc_STAN/ST_373.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp374.txt > ../../private_data/odnb_data_text/proc_STAN/ST_374.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp375.txt > ../../private_data/odnb_data_text/proc_STAN/ST_375.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp376.txt > ../../private_data/odnb_data_text/proc_STAN/ST_376.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp377.txt > ../../private_data/odnb_data_text/proc_STAN/ST_377.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp378.txt > ../../private_data/odnb_data_text/proc_STAN/ST_378.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp379.txt > ../../private_data/odnb_data_text/proc_STAN/ST_379.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp380.txt > ../../private_data/odnb_data_text/proc_STAN/ST_380.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp381.txt > ../../private_data/odnb_data_text/proc_STAN/ST_381.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp382.txt > ../../private_data/odnb_data_text/proc_STAN/ST_382.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp383.txt > ../../private_data/odnb_data_text/proc_STAN/ST_383.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp384.txt > ../../private_data/odnb_data_text/proc_STAN/ST_384.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp385.txt > ../../private_data/odnb_data_text/proc_STAN/ST_385.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp386.txt > ../../private_data/odnb_data_text/proc_STAN/ST_386.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp387.txt > ../../private_data/odnb_data_text/proc_STAN/ST_387.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp388.txt > ../../private_data/odnb_data_text/proc_STAN/ST_388.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp389.txt > ../../private_data/odnb_data_text/proc_STAN/ST_389.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp390.txt > ../../private_data/odnb_data_text/proc_STAN/ST_390.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp391.txt > ../../private_data/odnb_data_text/proc_STAN/ST_391.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp392.txt > ../../private_data/odnb_data_text/proc_STAN/ST_392.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp393.txt > ../../private_data/odnb_data_text/proc_STAN/ST_393.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp394.txt > ../../private_data/odnb_data_text/proc_STAN/ST_394.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp395.txt > ../../private_data/odnb_data_text/proc_STAN/ST_395.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp396.txt > ../../private_data/odnb_data_text/proc_STAN/ST_396.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp397.txt > ../../private_data/odnb_data_text/proc_STAN/ST_397.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp398.txt > ../../private_data/odnb_data_text/proc_STAN/ST_398.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp399.txt > ../../private_data/odnb_data_text/proc_STAN/ST_399.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp400.txt > ../../private_data/odnb_data_text/proc_STAN/ST_400.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp401.txt > ../../private_data/odnb_data_text/proc_STAN/ST_401.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp402.txt > ../../private_data/odnb_data_text/proc_STAN/ST_402.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp403.txt > ../../private_data/odnb_data_text/proc_STAN/ST_403.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp404.txt > ../../private_data/odnb_data_text/proc_STAN/ST_404.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp405.txt > ../../private_data/odnb_data_text/proc_STAN/ST_405.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp406.txt > ../../private_data/odnb_data_text/proc_STAN/ST_406.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp407.txt > ../../private_data/odnb_data_text/proc_STAN/ST_407.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp408.txt > ../../private_data/odnb_data_text/proc_STAN/ST_408.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp409.txt > ../../private_data/odnb_data_text/proc_STAN/ST_409.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp410.txt > ../../private_data/odnb_data_text/proc_STAN/ST_410.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp411.txt > ../../private_data/odnb_data_text/proc_STAN/ST_411.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp412.txt > ../../private_data/odnb_data_text/proc_STAN/ST_412.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp413.txt > ../../private_data/odnb_data_text/proc_STAN/ST_413.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp414.txt > ../../private_data/odnb_data_text/proc_STAN/ST_414.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp415.txt > ../../private_data/odnb_data_text/proc_STAN/ST_415.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp416.txt > ../../private_data/odnb_data_text/proc_STAN/ST_416.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp417.txt > ../../private_data/odnb_data_text/proc_STAN/ST_417.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp418.txt > ../../private_data/odnb_data_text/proc_STAN/ST_418.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp419.txt > ../../private_data/odnb_data_text/proc_STAN/ST_419.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp420.txt > ../../private_data/odnb_data_text/proc_STAN/ST_420.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp421.txt > ../../private_data/odnb_data_text/proc_STAN/ST_421.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp422.txt > ../../private_data/odnb_data_text/proc_STAN/ST_422.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp423.txt > ../../private_data/odnb_data_text/proc_STAN/ST_423.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp424.txt > ../../private_data/odnb_data_text/proc_STAN/ST_424.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp425.txt > ../../private_data/odnb_data_text/proc_STAN/ST_425.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp426.txt > ../../private_data/odnb_data_text/proc_STAN/ST_426.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp427.txt > ../../private_data/odnb_data_text/proc_STAN/ST_427.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp428.txt > ../../private_data/odnb_data_text/proc_STAN/ST_428.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp429.txt > ../../private_data/odnb_data_text/proc_STAN/ST_429.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp430.txt > ../../private_data/odnb_data_text/proc_STAN/ST_430.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp431.txt > ../../private_data/odnb_data_text/proc_STAN/ST_431.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp432.txt > ../../private_data/odnb_data_text/proc_STAN/ST_432.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp433.txt > ../../private_data/odnb_data_text/proc_STAN/ST_433.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp434.txt > ../../private_data/odnb_data_text/proc_STAN/ST_434.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp435.txt > ../../private_data/odnb_data_text/proc_STAN/ST_435.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp436.txt > ../../private_data/odnb_data_text/proc_STAN/ST_436.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp437.txt > ../../private_data/odnb_data_text/proc_STAN/ST_437.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp438.txt > ../../private_data/odnb_data_text/proc_STAN/ST_438.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp439.txt > ../../private_data/odnb_data_text/proc_STAN/ST_439.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp440.txt > ../../private_data/odnb_data_text/proc_STAN/ST_440.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp441.txt > ../../private_data/odnb_data_text/proc_STAN/ST_441.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp442.txt > ../../private_data/odnb_data_text/proc_STAN/ST_442.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp443.txt > ../../private_data/odnb_data_text/proc_STAN/ST_443.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp444.txt > ../../private_data/odnb_data_text/proc_STAN/ST_444.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp445.txt > ../../private_data/odnb_data_text/proc_STAN/ST_445.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp446.txt > ../../private_data/odnb_data_text/proc_STAN/ST_446.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp447.txt > ../../private_data/odnb_data_text/proc_STAN/ST_447.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp448.txt > ../../private_data/odnb_data_text/proc_STAN/ST_448.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp449.txt > ../../private_data/odnb_data_text/proc_STAN/ST_449.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp450.txt > ../../private_data/odnb_data_text/proc_STAN/ST_450.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp451.txt > ../../private_data/odnb_data_text/proc_STAN/ST_451.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp452.txt > ../../private_data/odnb_data_text/proc_STAN/ST_452.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp453.txt > ../../private_data/odnb_data_text/proc_STAN/ST_453.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp454.txt > ../../private_data/odnb_data_text/proc_STAN/ST_454.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp455.txt > ../../private_data/odnb_data_text/proc_STAN/ST_455.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp456.txt > ../../private_data/odnb_data_text/proc_STAN/ST_456.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp457.txt > ../../private_data/odnb_data_text/proc_STAN/ST_457.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp458.txt > ../../private_data/odnb_data_text/proc_STAN/ST_458.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp459.txt > ../../private_data/odnb_data_text/proc_STAN/ST_459.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp460.txt > ../../private_data/odnb_data_text/proc_STAN/ST_460.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp461.txt > ../../private_data/odnb_data_text/proc_STAN/ST_461.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp462.txt > ../../private_data/odnb_data_text/proc_STAN/ST_462.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp463.txt > ../../private_data/odnb_data_text/proc_STAN/ST_463.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp464.txt > ../../private_data/odnb_data_text/proc_STAN/ST_464.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp465.txt > ../../private_data/odnb_data_text/proc_STAN/ST_465.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp466.txt > ../../private_data/odnb_data_text/proc_STAN/ST_466.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp467.txt > ../../private_data/odnb_data_text/proc_STAN/ST_467.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp468.txt > ../../private_data/odnb_data_text/proc_STAN/ST_468.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp469.txt > ../../private_data/odnb_data_text/proc_STAN/ST_469.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp470.txt > ../../private_data/odnb_data_text/proc_STAN/ST_470.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp471.txt > ../../private_data/odnb_data_text/proc_STAN/ST_471.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp472.txt > ../../private_data/odnb_data_text/proc_STAN/ST_472.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp473.txt > ../../private_data/odnb_data_text/proc_STAN/ST_473.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp474.txt > ../../private_data/odnb_data_text/proc_STAN/ST_474.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp475.txt > ../../private_data/odnb_data_text/proc_STAN/ST_475.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp476.txt > ../../private_data/odnb_data_text/proc_STAN/ST_476.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp477.txt > ../../private_data/odnb_data_text/proc_STAN/ST_477.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp478.txt > ../../private_data/odnb_data_text/proc_STAN/ST_478.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp479.txt > ../../private_data/odnb_data_text/proc_STAN/ST_479.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp480.txt > ../../private_data/odnb_data_text/proc_STAN/ST_480.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp481.txt > ../../private_data/odnb_data_text/proc_STAN/ST_481.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp482.txt > ../../private_data/odnb_data_text/proc_STAN/ST_482.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp483.txt > ../../private_data/odnb_data_text/proc_STAN/ST_483.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp484.txt > ../../private_data/odnb_data_text/proc_STAN/ST_484.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp485.txt > ../../private_data/odnb_data_text/proc_STAN/ST_485.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp486.txt > ../../private_data/odnb_data_text/proc_STAN/ST_486.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp487.txt > ../../private_data/odnb_data_text/proc_STAN/ST_487.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp488.txt > ../../private_data/odnb_data_text/proc_STAN/ST_488.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp489.txt > ../../private_data/odnb_data_text/proc_STAN/ST_489.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp490.txt > ../../private_data/odnb_data_text/proc_STAN/ST_490.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp491.txt > ../../private_data/odnb_data_text/proc_STAN/ST_491.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp492.txt > ../../private_data/odnb_data_text/proc_STAN/ST_492.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp493.txt > ../../private_data/odnb_data_text/proc_STAN/ST_493.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp494.txt > ../../private_data/odnb_data_text/proc_STAN/ST_494.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp495.txt > ../../private_data/odnb_data_text/proc_STAN/ST_495.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp496.txt > ../../private_data/odnb_data_text/proc_STAN/ST_496.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp497.txt > ../../private_data/odnb_data_text/proc_STAN/ST_497.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp498.txt > ../../private_data/odnb_data_text/proc_STAN/ST_498.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp499.txt > ../../private_data/odnb_data_text/proc_STAN/ST_499.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp500.txt > ../../private_data/odnb_data_text/proc_STAN/ST_500.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp501.txt > ../../private_data/odnb_data_text/proc_STAN/ST_501.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp502.txt > ../../private_data/odnb_data_text/proc_STAN/ST_502.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp503.txt > ../../private_data/odnb_data_text/proc_STAN/ST_503.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp504.txt > ../../private_data/odnb_data_text/proc_STAN/ST_504.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp505.txt > ../../private_data/odnb_data_text/proc_STAN/ST_505.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp506.txt > ../../private_data/odnb_data_text/proc_STAN/ST_506.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp507.txt > ../../private_data/odnb_data_text/proc_STAN/ST_507.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp508.txt > ../../private_data/odnb_data_text/proc_STAN/ST_508.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp509.txt > ../../private_data/odnb_data_text/proc_STAN/ST_509.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp510.txt > ../../private_data/odnb_data_text/proc_STAN/ST_510.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp511.txt > ../../private_data/odnb_data_text/proc_STAN/ST_511.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp512.txt > ../../private_data/odnb_data_text/proc_STAN/ST_512.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp513.txt > ../../private_data/odnb_data_text/proc_STAN/ST_513.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp514.txt > ../../private_data/odnb_data_text/proc_STAN/ST_514.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp515.txt > ../../private_data/odnb_data_text/proc_STAN/ST_515.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp516.txt > ../../private_data/odnb_data_text/proc_STAN/ST_516.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp517.txt > ../../private_data/odnb_data_text/proc_STAN/ST_517.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp518.txt > ../../private_data/odnb_data_text/proc_STAN/ST_518.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp519.txt > ../../private_data/odnb_data_text/proc_STAN/ST_519.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp520.txt > ../../private_data/odnb_data_text/proc_STAN/ST_520.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp521.txt > ../../private_data/odnb_data_text/proc_STAN/ST_521.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp522.txt > ../../private_data/odnb_data_text/proc_STAN/ST_522.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp523.txt > ../../private_data/odnb_data_text/proc_STAN/ST_523.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp524.txt > ../../private_data/odnb_data_text/proc_STAN/ST_524.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp525.txt > ../../private_data/odnb_data_text/proc_STAN/ST_525.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp526.txt > ../../private_data/odnb_data_text/proc_STAN/ST_526.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp527.txt > ../../private_data/odnb_data_text/proc_STAN/ST_527.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp528.txt > ../../private_data/odnb_data_text/proc_STAN/ST_528.txt
sh ../../software/stanNER/ner.sh ../../private_data/odnb_data_text/COMPILED/comp529.txt > ../../private_data/odnb_data_text/proc_STAN/ST_529.txt
