#!/bin/sh
scriptdir=`dirname $0`

sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/1.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_1.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/2.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_2.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/3.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_3.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/4.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_4.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/5.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_5.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/6.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_6.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/7.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_7.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/8.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_8.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/9.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_9.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/10.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_10.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/11.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_11.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/12.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_12.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/13.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_13.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/14.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_14.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/15.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_15.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/16.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_16.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/17.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_17.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/18.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_18.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/19.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_19.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/20.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_20.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/21.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_21.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/22.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_22.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/23.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_23.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/24.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_24.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/25.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_25.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/26.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_26.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/27.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_27.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/28.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_28.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/29.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_29.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/30.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_30.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/31.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_31.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/32.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_32.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/33.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_33.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/34.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_34.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/35.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_35.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/36.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_36.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/37.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_37.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/38.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_38.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/39.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_39.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/40.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_40.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/41.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_41.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/42.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_42.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/43.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_43.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/44.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_44.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/45.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_45.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/46.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_46.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/47.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_47.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/48.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_48.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/49.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_49.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/50.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_50.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/51.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_51.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/52.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_52.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/53.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_53.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/54.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_54.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/55.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_55.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/56.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_56.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/57.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_57.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/58.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_58.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/59.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_59.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/60.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_60.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/61.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_61.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/62.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_62.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/63.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_63.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/64.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_64.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/65.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_65.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/66.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_66.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/67.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_67.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/68.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_68.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/69.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_69.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/70.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_70.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/71.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_71.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/72.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_72.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/73.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_73.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/74.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_74.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/75.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_75.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/76.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_76.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/77.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_77.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/78.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_78.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/79.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_79.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/80.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_80.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/81.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_81.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/82.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_82.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/83.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_83.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/84.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_84.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/85.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_85.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/86.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_86.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/87.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_87.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/88.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_88.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/89.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_89.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/90.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_90.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/91.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_91.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/92.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_92.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/93.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_93.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/94.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_94.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/95.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_95.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/96.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_96.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/97.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_97.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/98.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_98.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/99.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_99.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/100.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_100.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/101.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_101.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/102.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_102.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/103.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_103.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/104.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_104.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/105.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_105.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/106.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_106.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/107.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_107.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/108.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_108.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/109.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_109.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/110.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_110.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/111.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_111.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/112.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_112.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/113.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_113.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/114.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_114.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/115.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_115.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/116.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_116.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/117.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_117.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/118.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_118.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/119.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_119.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/120.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_120.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/121.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_121.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/122.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_122.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/123.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_123.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/124.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_124.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/125.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_125.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/126.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_126.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/127.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_127.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/128.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_128.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/129.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_129.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/130.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_130.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/131.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_131.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/132.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_132.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/133.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_133.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/134.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_134.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/135.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_135.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/136.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_136.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/137.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_137.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/138.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_138.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/139.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_139.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/140.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_140.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/141.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_141.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/142.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_142.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/143.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_143.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/144.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_144.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/145.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_145.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/146.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_146.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/147.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_147.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/148.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_148.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/149.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_149.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/150.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_150.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/151.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_151.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/152.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_152.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/153.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_153.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/154.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_154.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/155.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_155.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/156.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_156.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/157.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_157.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/158.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_158.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/159.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_159.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/160.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_160.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/161.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_161.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/162.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_162.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/163.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_163.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/164.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_164.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/165.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_165.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/166.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_166.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/167.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_167.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/168.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_168.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/169.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_169.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/170.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_170.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/171.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_171.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/172.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_172.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/173.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_173.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/174.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_174.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/175.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_175.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/176.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_176.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/177.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_177.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/178.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_178.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/179.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_179.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/180.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_180.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/181.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_181.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/182.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_182.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/183.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_183.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/184.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_184.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/185.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_185.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/186.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_186.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/187.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_187.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/188.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_188.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/189.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_189.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/190.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_190.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/191.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_191.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/192.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_192.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/193.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_193.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/194.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_194.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/195.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_195.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/196.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_196.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/197.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_197.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/198.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_198.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/199.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_199.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/200.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_200.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/201.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_201.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/202.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_202.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/203.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_203.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/204.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_204.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/205.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_205.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/206.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_206.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/207.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_207.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/208.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_208.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/209.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_209.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/210.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_210.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/211.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_211.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/212.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_212.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/213.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_213.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/214.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_214.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/215.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_215.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/216.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_216.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/217.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_217.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/218.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_218.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/219.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_219.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/220.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_220.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/221.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_221.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/222.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_222.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/223.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_223.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/224.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_224.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/225.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_225.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/226.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_226.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/227.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_227.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/228.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_228.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/229.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_229.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/230.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_230.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/231.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_231.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/232.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_232.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/233.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_233.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/234.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_234.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/235.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_235.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/236.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_236.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/237.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_237.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/238.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_238.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/239.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_239.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/240.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_240.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/241.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_241.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/242.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_242.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/243.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_243.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/244.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_244.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/245.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_245.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/246.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_246.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/247.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_247.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/248.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_248.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/249.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_249.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/250.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_250.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/251.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_251.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/252.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_252.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/253.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_253.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/254.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_254.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/255.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_255.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/256.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_256.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/257.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_257.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/258.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_258.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/259.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_259.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/260.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_260.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/261.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_261.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/262.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_262.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/263.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_263.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/264.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_264.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/265.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_265.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/266.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_266.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/267.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_267.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/268.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_268.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/269.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_269.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/270.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_270.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/271.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_271.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/272.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_272.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/273.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_273.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/274.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_274.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/275.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_275.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/276.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_276.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/277.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_277.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/278.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_278.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/279.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_279.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/280.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_280.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/281.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_281.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/282.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_282.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/283.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_283.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/284.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_284.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/285.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_285.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/286.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_286.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/287.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_287.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/288.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_288.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/289.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_289.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/290.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_290.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/291.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_291.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/292.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_292.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/293.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_293.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/294.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_294.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/295.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_295.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/296.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_296.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/297.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_297.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/298.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_298.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/299.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_299.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/300.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_300.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/301.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_301.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/302.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_302.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/303.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_303.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/304.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_304.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/305.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_305.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/306.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_306.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/307.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_307.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/308.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_308.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/309.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_309.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/310.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_310.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/311.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_311.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/312.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_312.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/313.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_313.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/314.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_314.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/315.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_315.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/316.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_316.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/317.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_317.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/318.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_318.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/319.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_319.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/320.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_320.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/321.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_321.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/322.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_322.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/323.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_323.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/324.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_324.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/325.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_325.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/326.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_326.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/327.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_327.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/328.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_328.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/329.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_329.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/330.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_330.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/331.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_331.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/332.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_332.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/333.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_333.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/334.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_334.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/335.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_335.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/336.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_336.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/337.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_337.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/338.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_338.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/339.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_339.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/340.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_340.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/341.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_341.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/342.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_342.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/343.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_343.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/344.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_344.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/345.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_345.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/346.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_346.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/347.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_347.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/348.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_348.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/349.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_349.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/350.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_350.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/351.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_351.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/352.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_352.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/353.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_353.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/354.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_354.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/355.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_355.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/356.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_356.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/357.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_357.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/358.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_358.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/359.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_359.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/360.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_360.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/361.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_361.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/362.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_362.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/363.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_363.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/364.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_364.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/365.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_365.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/366.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_366.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/367.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_367.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/368.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_368.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/369.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_369.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/370.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_370.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/371.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_371.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/372.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_372.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/373.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_373.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/374.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_374.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/375.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_375.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/376.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_376.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/377.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_377.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/378.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_378.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/379.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_379.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/380.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_380.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/381.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_381.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/382.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_382.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/383.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_383.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/384.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_384.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/385.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_385.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/386.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_386.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/387.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_387.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/388.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_388.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/389.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_389.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/390.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_390.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/391.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_391.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/392.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_392.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/393.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_393.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/394.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_394.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/395.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_395.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/396.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_396.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/397.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_397.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/398.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_398.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/399.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_399.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/400.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_400.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/401.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_401.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/402.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_402.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/403.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_403.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/404.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_404.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/405.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_405.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/406.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_406.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/407.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_407.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/408.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_408.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/409.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_409.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/410.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_410.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/411.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_411.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/412.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_412.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/413.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_413.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/414.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_414.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/415.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_415.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/416.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_416.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/417.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_417.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/418.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_418.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/419.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_419.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/420.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_420.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/421.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_421.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/422.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_422.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/423.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_423.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/424.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_424.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/425.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_425.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/426.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_426.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/427.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_427.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/428.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_428.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/429.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_429.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/430.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_430.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/431.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_431.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/432.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_432.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/433.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_433.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/434.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_434.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/435.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_435.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/436.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_436.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/437.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_437.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/438.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_438.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/439.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_439.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/440.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_440.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/441.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_441.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/442.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_442.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/443.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_443.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/444.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_444.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/445.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_445.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/446.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_446.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/447.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_447.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/448.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_448.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/449.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_449.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/450.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_450.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/451.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_451.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/452.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_452.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/453.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_453.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/454.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_454.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/455.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_455.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/456.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_456.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/457.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_457.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/458.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_458.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/459.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_459.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/460.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_460.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/461.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_461.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/462.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_462.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/463.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_463.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/464.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_464.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/465.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_465.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/466.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_466.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/467.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_467.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/468.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_468.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/469.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_469.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/470.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_470.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/471.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_471.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/472.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_472.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/473.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_473.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/474.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_474.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/475.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_475.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/476.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_476.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/477.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_477.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/478.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_478.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/479.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_479.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/480.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_480.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/481.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_481.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/482.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_482.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/483.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_483.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/484.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_484.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/485.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_485.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/486.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_486.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/487.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_487.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/488.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_488.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/489.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_489.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/490.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_490.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/491.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_491.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/492.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_492.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/493.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_493.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/494.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_494.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/495.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_495.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/496.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_496.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/497.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_497.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/498.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_498.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/499.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_499.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/500.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_500.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/501.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_501.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/502.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_502.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/503.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_503.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/504.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_504.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/505.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_505.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/506.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_506.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/507.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_507.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/508.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_508.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/509.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_509.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/510.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_510.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/511.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_511.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/512.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_512.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/513.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_513.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/514.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_514.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/515.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_515.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/516.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_516.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/517.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_517.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/518.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_518.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/519.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_519.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/520.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_520.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/521.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_521.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/522.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_522.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/523.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_523.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/524.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_524.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/525.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_525.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/526.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_526.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/527.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_527.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/528.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_528.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/529.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_529.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/530.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_530.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/531.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_531.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/532.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_532.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/533.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_533.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/534.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_534.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/535.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_535.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/536.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_536.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/537.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_537.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/538.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_538.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/539.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_539.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/540.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_540.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/541.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_541.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/542.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_542.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/543.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_543.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/544.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_544.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/545.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_545.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/546.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_546.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/547.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_547.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/548.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_548.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/549.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_549.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/550.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_550.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/551.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_551.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/552.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_552.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/553.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_553.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/554.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_554.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/555.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_555.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/556.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_556.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/557.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_557.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/558.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_558.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/559.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_559.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/560.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_560.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/561.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_561.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/562.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_562.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/563.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_563.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/564.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_564.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/565.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_565.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/566.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_566.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/567.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_567.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/568.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_568.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/569.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_569.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/570.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_570.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/571.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_571.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/572.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_572.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/573.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_573.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/574.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_574.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/575.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_575.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/576.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_576.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/577.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_577.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/578.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_578.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/579.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_579.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/580.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_580.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/581.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_581.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/582.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_582.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/583.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_583.txt
sh ../../../../software/stanNER/ner.sh ../../../../data/ODNB_intermediate/NER/compiled_raw/584.txt > ../../../../data/ODNB_intermediate/NER/proc_STAN/ST_584.txt
